config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models
from users import models as user_models


class AbstractItem(core_models.AbstractTimeStamp):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """ RoomType Model Definition """

    class Meta:
        verbose_name = "Room Types"


class Amenity(AbstractItem):

    """ Amenity Model Definition """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """ Facility Model Definition """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """ House Model Definition """

    class Meta:
        verbose_name = "House Rules"


class Photo(core_models.AbstractTimeStamp):

    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.AbstractTimeStamp, models.Model):

    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    bath = models.IntegerField()
    guests = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        # related_name 은 Foreign Key에서 어떻게 접근했으면 좋겠는지 정해준다. 안정해주면 _set이 default다
        user_models.User,
        related_name="rooms",
        on_delete=models.CASCADE,
    )
    room_type = models.ForeignKey(
        RoomType, related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField(Amenity, related_name="rooms", blank=True)
    facilities = models.ManyToManyField(Facility, related_name="rooms", blank=True)
    house_rules = models.ManyToManyField(HouseRule, related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        for review in all_reviews:
            all_ratings += review.rating_average()
        if not len(all_reviews):
            return "No reviews"
        return round(all_ratings / len(all_reviews), 2)

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="AnyWhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        empty_label="Any Kind", queryset=models.RoomType.objects.all(), required=False
    )
    price = forms.IntegerField(required=False)
    guest = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

rooms/views.py
"""

#  Function Based Views

from math import ceil
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage
from . import models
from django.http import Http404


def all_rooms(request):
    page = request.GET.get("page", 1)
    room_list = models.Room.objects.all()
    paginator = Paginator(room_list, 10, orphans=6)
    try:
        rooms = paginator.page(int(page))
        return render(request, "rooms/home.html", {"page": rooms})

    except EmptyPage or InvalidPage or PageNotAnInteger:
        return redirect("/")


def room_detail(request, pk):
    try:
        room = models.Room.objects.get(pk=pk)
        return render(request, "rooms/detail.html", {"room": room})
    except models.Room.DoesNotExist:
        raise Http404()

"""

"""

FBV not using Django Form

def search(request):
    city = request.GET.get("city", "anywhere")
    country = request.GET.get("country", "KR")
    room_type = int(request.GET.get("room_type", 0))
    price = int(request.GET.get("price", 0))
    guests = int(request.GET.get("guests", 0))
    bedrooms = int(request.GET.get("bedrooms", 0))
    beds = int(request.GET.get("beds", 0))
    bath = int(request.GET.get("bath", 0))
    instant = bool(request.GET.get("instant", False))
    superhost = bool(request.GET.get("superhost", False))
    form = {
        "city": city,
        "selected_room_type": room_type,
        "selected_country": country,
        "price": price,
        "guests": guests,
        "bedrooms": bedrooms,
        "beds": beds,
        "bath": bath,
        "instant": instant,

        "superhost": superhost,
    }

    room_types = models.RoomType.objects.all()
    amenities = models.Amenity.objects.all()
    facilities = models.Facility.objects.all()

    selected_amenities = request.GET.getlist("amenities")
    selected_facilities = request.GET.getlist("facilities")

    choices = {
        "countries": countries,
        "room_types": room_types,
        "amenities": amenities,
        "facilities": facilities,
        "selected_amenities": selected_amenities,
        "selected_facilities": selected_facilities,
    }

    filter_args = {}

    if city != "Anywhere":
        filter_args["city__startswith"] = city

    filter_args["country"] = country

    if room_type is not None:
        filter_args["room_type__pk"] = room_type

    if price is not None:
        filter_args["price__lte"] = price
    if guests is not None:
        filter_args["guests__gte"] = guests

    if bedrooms is not None:
        filter_args["bedrooms__gte"] = bedrooms

    if beds is not None:
        filter_args["beds__gte"] = beds

    if bath is not None:
        filter_args["bath__gte"] = bath

    if instant is True:
        filter_args["instant_book"] = True

    if superhost is True:
        filter_args["host__superhost"] = True

    if selected_amenities is not None:
        for s_amenity in selected_amenities:
            filter_args["amenities__pk"] = int(s_amenity)

    if selected_facilities is not None:
        for facility in selected_facilities:
            filter_args["facilities__pk"] = int(facility)

    rooms = models.Room.objects.filter(**filter_args)

    return render(
        request,
        "rooms/search.html",
        context={
            **form,
            **choices,
            "rooms": rooms,
        },
    )
"""

"""

FBV using Django Form
def search(request):

    country = request.GET.get("country")

    if country:
        form = forms.SearchForm(request.GET)
        if form.is_valid():
            city = form.cleaned_data.get("city")
            country = form.cleaned_data.get("country")
            room_type = form.cleaned_data.get("room_type")
            price = form.cleaned_data.get("price")
            guests = form.cleaned_data.get("guests")
            bedrooms = form.cleaned_data.get("bedrooms")
            beds = form.cleaned_data.get("beds")
            bath = form.cleaned_data.get("bath")
            instant_book = form.cleaned_data.get("instant_book")
            superhost = form.cleaned_data.get("superhost")
            amenities = form.cleaned_data.get("amenities")
            facilities = form.cleaned_data.get("facilities")

            filter_args = {}

            if city != "Anywhere":
                filter_args["city__startswith"] = city

            filter_args["country"] = country

            if room_type is not None:
                filter_args["room_type"] = room_type

            if price is not None:
                filter_args["price__lte"] = price
            if guests is not None:
                filter_args["guests__gte"] = guests

            if bedrooms is not None:
                filter_args["bedrooms__gte"] = bedrooms

            if beds is not None:
                filter_args["beds__gte"] = beds

            if bath is not None:
                filter_args["bath__gte"] = bath

            if instant_book is True:
                filter_args["instant_book"] = True

            if superhost is True:
                filter_args["host__superhost"] = True

            for amenity in amenities:
                filter_args["amenities"] = amenity

            for facility in facilities:
                filter_args["facilities"] = facility

            rooms = models.Room.objects.filter(**filter_args)
    else:
        form = forms.SearchForm()
    return render(request, "rooms/search.html", {"form": form, "rooms": rooms})
"""

#  Class Based Views
from django.shortcuts import render
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView, View
from django_countries import countries
from . import models, forms


class HomeView(ListView):

    model = models.Room
    paginate_by = 10
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"


class RoomDetail(DetailView):

    model = models.Room


class SearchView(View):
    def get(self, request):
        country = request.GET.get("country")

        if country:
            form = forms.SearchForm(request.GET)
            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                bath = form.cleaned_data.get("bath")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price
                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if bath is not None:
                    filter_args["bath__gte"] = bath

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = models.Room.objects.filter(**filter_args).order_by("-created ")
                paginator = Paginator(qs, 10, orphans=5)
                page = request.GET.get("page", 1)
                rooms = paginator.get_page(page)
                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )

        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html", {"form": form})

templates/rooms/room_detail.html
{% extends 'base.html' %}

{% block page_title %}
    {{room.name}}
{% endblock page_title %}

{% block content %}
<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
</div>
<div>
    <h2>
        By: {{room.host.username}}
        {% if room.host.superhost %}
            {superhost}
        {% endif %}
    </h2>
    <h3>Amenities</h3>
    <ul>
    {% for a in room.amenities.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>Facilites</h3>

    <ul>
    {% for a in room.facilities.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>House Rule</h3>

    <ul>
    {% for a in room.house_rules.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>

</div>
{% endblock content %}

templates/rooms/room_list.html
{% extends 'base.html' %}

{% block page_title %}
    Home
{% endblock page_title %}

{% block content %}

    {% for room in rooms %}
        <h3>
            <a href="{% url "rooms:detail" room.pk %}">
                {{room.name}} / ${{room.price}}
            </a>
        </h3>
    {% endfor %}

    <h5>
        {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}">Previous</a>
        {% endif %}

            Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}">Next</a>
        {% endif %}

     </h5>

{% endblock content %}

templates/rooms/search-notUsingDjangoForm.html
{% extends 'base.html' %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <h2>Search!</h2>


    <form method="get" action="{% url "rooms:search" %}">

        <div>
            <lable for="city">City </lable>
            <input value="{{city}}" id="city" name="city" placeholder="Search by city" />
        </div>

        <div>
            <lable for="country">Country </lable>
            <select id="country" name="country">
                {% for country in countries %}
                    <option value="{{country.code}}" {% if country.code == selected_country %}selected{% endif %}>{{country.name}} </option>
                {% endfor %}
            </select>
        </div>

        <div>
            <lable for="room_type">Room Type </lable>
            <select id="room_type" name="room_type">
            <option value="0" {% if selected_room_type == 0 %} selected {% endif %}>Any Kind</option>
                {% for room_type in room_types %}
                    <option value="{{room_type.pk}}" {% if selected_room_type == room_type.pk %} selected {% endif %}> {{room_type.name}} </option>
                {% endfor %}
            </select>
        </div>

        <div>
            <lable for="price">Price</lable>
            <input value="{{price}}" type="number" name="price" id="price" placeholder="Price" />
        </div>

        <div>
            <lable for="guest">Guest</lable>
            <input value="{{guest}}" type="number" name="guest" id="guest" placeholder="Guest" />
        </div>

        <div>
            <lable for="bedrooms">Bedrooms</lable>
            <input value="{{bedrooms}}" type="number" name="bedrooms" id="bedrooms" placeholder="Bedrooms" />
        </div>

        <div>
            <lable for="beds">Beds</lable>
            <input value="{{beds}}" type="number" name="beds" id="beds" placeholder="Beds" />
        </div>

        <div>
            <lable for="baths">Baths</lable>
            <input value="{{baths}}" type="number" name="baths" id="baths" placeholder="Baths" />
        </div>

        <div>
            <label for="instant">Instant Book Only?</lable>
            <input type="checkbox" name="instant" id="instant" {% if instant%}checked{% endif %} />
        </div>

        <div>
            <label for="superhost">By superhost Only?</lable>
            <input type="checkbox" name="superhost" id="superhost" {% if superhost %}checked{% endif %} />
        </div>

        <div>
            <h3>Amenities</h3>
            <ul>
                {% for amenity in amenities %}
                    <li>
                        <label for="a_{{amenity.pk}} ">{{amenity.name}}</lable>
                        <input
                            id="a_{{amenity.pk}}"
                            name="amenities"
                            type="checkbox"
                            value="{{amenity.pk}}"
                            {% if amenity.pk|slugify in selected_amenities %}checked{% endif %}
                        />
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div>
            <h3>Facilities</h3>
            <ul>
                {% for facility in facilities %}
                    <li>
                        <label for="f_{{facility.pk}} ">{{facility.name}}</lable>
                        <input
                            id="f_{{facility.pk}}"
                            name="facilities"
                            type="checkbox"
                            value="{{facility.pk}}"
                            {% if facility.pk|slugify in selected_facilities %}checked{% endif %}
                        />
                    </li>
                {% endfor %}
            </ul>
        </div>

        <button>
            Search
        </button>

        <h3>Results</h3>

        {% for room in rooms %}
            <h3>{{room.name}}</h3>
        {% endfor %}

    </form>

{% endblock content %}

templates/rooms/search-selfmade.html
{% extends 'base.html' %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <h2>Search!</h2>


    <form method="get" action="{% url "rooms:search" %}">

        <div>
            <lable for="city">City </lable>
            <input value="{{city}}" id="city" name="city" placeholder="Search by city" />
        </div>

        <div>
            <lable for="country">Country </lable>
            <select id="country" name="country">
                {% for country in countries %}
                    <option value="{{country.code}}" {% if country.code == selected_country %}selected{% endif %}>{{country.name}} </option>
                {% endfor %}
            </select>
        </div>

        <div>
            <lable for="room_type">Room Type </lable>
            <select id="room_type" name="room_type">
            <option value="0" {% if selected_room_type == 0 %} selected {% endif %}>Any Kind</option>
                {% for room_type in room_types %}
                    <option value="{{room_type.pk}}" {% if selected_room_type == room_type.pk %} selected {% endif %}> {{room_type.name}} </option>
                {% endfor %}
            </select>
        </div>

        <div>
            <lable for="price">Price</lable>
            <input value="{{price}}" type="number" name="price" id="price" placeholder="Price" />
        </div>

        <div>
            <lable for="guest">Guest</lable>
            <input value="{{guest}}" type="number" name="guest" id="guest" placeholder="Guest" />
        </div>

        <div>
            <lable for="bedrooms">Bedrooms</lable>
            <input value="{{bedrooms}}" type="number" name="bedrooms" id="bedrooms" placeholder="Bedrooms" />
        </div>

        <div>
            <lable for="beds">Beds</lable>
            <input value="{{beds}}" type="number" name="beds" id="beds" placeholder="Beds" />
        </div>

        <div>
            <lable for="baths">Baths</lable>
            <input value="{{baths}}" type="number" name="baths" id="baths" placeholder="Baths" />
        </div>

        <div>
            <label for="instant">Instant Book Only?</lable>
            <input type="checkbox" name="instant" id="instant" {% if instant%}checked{% endif %} />
        </div>

        <div>
            <label for="superhost">By superhost Only?</lable>
            <input type="checkbox" name="superhost" id="superhost" {% if superhost %}checked{% endif %} />
        </div>

        <div>
            <h3>Amenities</h3>
            <ul>
                {% for amenity in amenities %}
                    <li>
                        <label for="a_{{amenity.pk}} ">{{amenity.name}}</lable>
                        <input
                            id="a_{{amenity.pk}}"
                            name="amenities"
                            type="checkbox"
                            value="{{amenity.pk}}"
                            {% if amenity.pk|slugify in selected_amenities %}checked{% endif %}
                        />
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div>
            <h3>Facilities</h3>
            <ul>
                {% for facility in facilities %}
                    <li>
                        <label for="f_{{facility.pk}} ">{{facility.name}}</lable>
                        <input
                            id="f_{{facility.pk}}"
                            name="facilities"
                            type="checkbox"
                            value="{{facility.pk}}"
                            {% if facility.pk|slugify in selected_facilities %}checked{% endif %}
                        />
                    </li>
                {% endfor %}
            </ul>
        </div>

        <button>
            Search
        </button>

        <h3>Results</h3>

        {% for room in rooms %}
            <h3>{{room.name}}</h3>
        {% endfor %}

    </form>

{% endblock content %}

templates/rooms/search.html
{% extends 'base.html' %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <h2>Search!</h2>


    <form method="get" action="{% url "rooms:search" %}">
        {{form.as_p}}
        <button>Search</button>

        <h3>Results</h3>

        {% for room in rooms %}
            <h3>{{room.name}}</h3>
        {% endfor %}

    </form>

{% endblock content %}